name: Generate Trophy

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: Humble-Librarian
          file: dist/trophy.svg
          theme: tokyonight
          no-frame: true
          no-background: true
          max-cols: 7
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
